/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "background": "#f9f9f9",
        "secondary": "#5e5e5e",
        "panel-bg": "#F3F2EF",
        "inverse-primary": "#c6c6c6",
        "error": "#ba1a1a",
        "on-surface-variant": "#4c4546",
        "on-surface": "#1b1b1b",
        "outline": "#7e7576",
        "secondary-container": "#e1dfdf",
        "tertiary-fixed": "#e2e2e2",
        "surface-tint": "#5e5e5e",
        "surface-container": "#eeeeee",
        "on-secondary-fixed": "#1b1c1c",
        "inverse-on-surface": "#f1f1f1",
        "on-tertiary-fixed-variant": "#474747",
        "secondary-fixed-dim": "#c7c6c6",
        "primary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c6",
        "card-bg": "#FCFCFB",
        "secondary-fixed": "#e4e2e2",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#464747",
        "on-primary-fixed-variant": "#474747",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "on-secondary-container": "#626262",
        "neural-pink": "#F43F5E",
        "tertiary-container": "#1b1b1b",
        "on-tertiary-container": "#848484",
        "surface-container-highest": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "neural-purple": "#8B5CF6",
        "on-primary-container": "#848484",
        "primary": "#000000",
        "canvas-bg": "#F7F7F5",
        "neural-blue": "#3B82F6",
        "on-tertiary": "#ffffff",
        "surface": "#f9f9f9",
        "on-background": "#1b1b1b",
        "on-error-container": "#93000a",
        "tertiary": "#000000",
        "success-emerald": "#10B981",
        "primary-container": "#1b1b1b",
        "border-subtle": "#E7E7E4",
        "surface-bright": "#f9f9f9",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#1b1b1b",
        "outline-variant": "#cfc4c5",
        "surface-variant": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "surface-dim": "#dadada",
        "surface-container-low": "#f3f3f3",
        "on-error": "#ffffff",
        "inverse-surface": "#303030"
      },
      "borderRadius": {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      "spacing": {
        "edge_margin": "32px",
        "unit_base": "8px",
        "section_gap_mobile": "80px",
        "section_gap_desktop": "180px",
        "gutter": "32px",
        "container_max": "1280px"
      },
      "fontFamily": {
        "mono-metrics": ["Geist", "monospace"],
        "h1": ["Geist", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "h1-mobile": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "h2-mobile": ["Geist", "sans-serif"],
        "h2": ["Geist", "sans-serif"],
        "h3": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "mono-metrics": ["12px", { "lineHeight": "1", "letterSpacing": "0", "fontWeight": "700" }],
        "h1": ["84px", { "lineHeight": "1.05", "letterSpacing": "-0.04em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "h1-mobile": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400" }],
        "h2-mobile": ["32px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "h2": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "h3": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
